name: Unit tests

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.16
        uses: actions/setup-java@v1
        with:
          java-version: 1.16
      - name: Compile
        run: mvn -B compile --file pom.xml
      - name: Unit tests
        run: mvn -B test --file pom.xml
